### ISSUE TITLE
Cordial Face Error

### ISSUE THREAD

**Issue by chrismbirmingham** [interaction-lab/HARMONI#21]
Issue with dialog on the refactor branch #20 

There is an issue with cordial being split into eyes and mouth while the configuration is for one node. This should either be split in the configuration or handled separately somehow.

Traceback:
`[INFO] [1599532561.234088]: Initializing the dialogue service
Traceback (most recent call last):
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_core/harmoni_pattern/scripts/harmoni_pattern/sequential_pattern.py", line 340, in <module>
    main()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_core/harmoni_pattern/scripts/harmoni_pattern/sequential_pattern.py", line 327, in main
    dp = SequentialPattern(pattern_name, script)
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_core/harmoni_pattern/scripts/harmoni_pattern/sequential_pattern.py", line 38, in __init__
    self._setup_clients()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_core/harmoni_pattern/scripts/harmoni_pattern/sequential_pattern.py", line 61, in _setup_clients
    ), f"Scripted service: {service}, has not been configured"
AssertionError: Scripted service: harmoni_face_mouth_default, has not been configured
[harmoni_pattern-1] process has died [pid 3498, exit code 1, cmd /root/harmoni_catkin_ws/src/HARMONI/harmoni_core/harmoni_pattern/scripts/harmoni_pattern/sequential_pattern.py false Hey default __name:=harmoni_pattern __log:=/root/.ros/log/9f768010-f17b-11ea-a428-0242ac120304/harmoni_pattern-1.log].
log file: /root/.ros/log/9f768010-f17b-11ea-a428-0242ac120304/harmoni_pattern-1*.log
`

**Comment by micolspitale93** [comment]
I think that the issue can be the pattern json. 
It seems you still have the old names (i.e., harmoni_face_mouth_default) instead of the new ones (i.e., face_mouth_default). In the pattern json (multiple_choice.json, and dialoging), you should rename the service name removing the "harmoni_" prefix. 
Maybe the json were in the gitignore, and so my updates have not been pushed.

**Comment by chrismbirmingham** [comment]
You were correct, I was unwittingly on an old commit. My bad! The json updates were in the commit. Having said that, I think that keeping the harmoni_decision/config/configuration.yaml file listing just a 'face' when two services actually get started is a little confusing. So I updated the documentation a bit, though it could probably use more.
