### ISSUE TITLE
Combine Face and Web Packages

### ISSUE THREAD

**Issue by RMichaelSwan** [interaction-lab/HARMONI#33]
Right now the packages are doing the same thing for server setup. The restructure involves making it so that the server can start whichever html is requested by an interaction and then work with it. This avoids having repeated code while allowing for an increasing number of custom html pages.

**Comment by micolspitale93** [comment]
Finally we have decided to keep them separate. We can close this issue.

**Comment by chrismbirmingham** [comment]
Done.
