### ISSUE TITLE
Remove test:=true references

### ISSUE THREAD

**Issue by RMichaelSwan** [interaction-lab/HARMONI#45]
Currently our dockerfile setup_script has a number of aliases for our old way of testing. These should be updated to reflect current rostest usage. In general anything that mentions the rosparam `test` (usually `test:=true`) should be updated/fixed.
https://github.com/interaction-lab/HARMONI/blob/609f52a21000d0884ac1654464dbc525e34d0145/dockerfiles/config/setup_script.sh#L24

**Comment by chrismbirmingham** [comment]
Also we appear to still have old references to test in the harmoni_decision package which need to be refactored. @micolspitale93 have you updated harmoni_decision in your fork to ensure the launcher.py works correctly with the new launch files?

**Comment by micolspitale93** [comment]
@chrismbirmingham I promise to work on both this issue and the cordial face stuff asap.

**Comment by micolspitale93** [comment]
I have addressed this issue in pull request #60
