### ISSUE TITLE
Launching Services Tutorial

### ISSUE THREAD

**Issue by RMichaelSwan** [interaction-lab/HARMONI#55]
The service launch documentation is currently a bit outdated. The aliases `setup_script.sh` aliases also need a rework based on recent changes.

> If we are including these in the docs they should be tested to make sure they still work (I think some are outdated)

_Originally posted by @chrismbirmingham in https://github.com/interaction-lab/HARMONI/pull/46#discussion_r633600302_

**Comment by chrismbirmingham** [comment]
Updated.
