### ISSUE TITLE
Quickstart build harmoni core packages roscpp cmake error

### ISSUE THREAD

**Issue by emdg05** [interaction-lab/HARMONI#58]
When attempting step 3 (build harmoni core packages) of desktop setup quickstart, this error happens for harmoni_recorder, harmoni_common_lib, harmoni_pattern, and harmoni_decision:

```
CMake Error at /home/multiparty/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "roscpp" with any
  of the following names:

    roscppConfig.cmake
    roscpp-config.cmake

  Add the installation prefix of "roscpp" to CMAKE_PREFIX_PATH or set
  "roscpp_DIR" to a directory containing one of the above files.  If "roscpp"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)
```

This error happens for harmoni_common_msgs:

```
CMake Error at /home/multiparty/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "rospy" with any of
  the following names:

    rospyConfig.cmake
    rospy-config.cmake

  Add the installation prefix of "rospy" to CMAKE_PREFIX_PATH or set
  "rospy_DIR" to a directory containing one of the above files.  If "rospy"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

```
Here's the summary:

```
[build] Summary: 1 of 6 packages succeeded.                                    
[build]   Ignored:   10 packages were skipped or are blacklisted.              
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    5 packages failed.                                        
[build] Runtime: 1.0 seconds total.  
```

**Comment by RMichaelSwan** [comment]
> When attempting step 3 (build harmoni core packages) of desktop setup quickstart, this error happens for harmoni_recorder, harmoni_common_lib, harmoni_pattern, and harmoni_decision:
> 
> ```
> CMake Error at /home/multiparty/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "roscpp" with any
>   of the following names:
> 
>     roscppConfig.cmake
>     roscpp-config.cmake
> 
>   Add the installation prefix of "roscpp" to CMAKE_PREFIX_PATH or set
>   "roscpp_DIR" to a directory containing one of the above files.  If "roscpp"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:10 (find_package)
> ```
> 
> This error happens for harmoni_common_msgs:
> 
> ```
> CMake Error at /home/multiparty/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "rospy" with any of
>   the following names:
> 
>     rospyConfig.cmake
>     rospy-config.cmake
> 
>   Add the installation prefix of "rospy" to CMAKE_PREFIX_PATH or set
>   "rospy_DIR" to a directory containing one of the above files.  If "rospy"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:10 (find_package)
> ```
> 
> Here's the summary:
> 
> ```
> [build] Summary: 1 of 6 packages succeeded.                                    
> [build]   Ignored:   10 packages were skipped or are blacklisted.              
> [build]   Warnings:  None.                                                     
> [build]   Abandoned: None.                                                     
> [build]   Failed:    5 packages failed.                                        
> [build] Runtime: 1.0 seconds total.  
> ```

What system are you running it on? What CPU, OS? What version of docker and version of docker-compose?

**Comment by chrismbirmingham** [comment]
This was while attempting a local install of kinetic on ubuntu 16.04. The docs have been updated to include the `-DPYTHON_EXECUTABLE=/usr/bin/python3` which is needed for ensuring use of python 3.
