### ISSUE TITLE
Cannot play audio on dockerfiles

### ISSUE THREAD

**Issue by micolspitale93** [interaction-lab/HARMONI#6]
Command: aplay tts.wav

Error message is: ALSA lib pcm_dmix.c:1029: (snd_pcm_dmix_open) unable to open slave aplay: main:722: audio open error: No such file or directory

**Comment by chrismbirmingham** [comment]
Can you add the command you were using?

**Comment by micolspitale93** [comment]
Command: aplay tts.wav

**Comment by chrismbirmingham** [comment]
Thanks. I tried to duplicate and was able to play the sound just fine. Can you check playing on your Ubuntu 20 system? Also, try `alsa force-reload`

**Comment by micolspitale93** [comment]
I realize that also in my machine was  not working.
It did not recognize my speaker as the default one (it takes the HDMI port instead), and so I set my default card device in the asound.conf file. I followed this instructions:
- Check which the card device number you want to set as default
`aplay -l`

- Create a config file to set the default device

```
cd /etc/ 
nano asound.conf
```
- Copy and paste the following, changing the card number according to your default sound device 
```
pcm.!default {
        type plug
        slave {
                pcm "hw:0,0"
        }
}

ctl.!default {
        type hw
        card 0
}

```
I made the same setup also in the docker container, and now it works

**Comment by chrismbirmingham** [comment]
Excellent, I will close this issue then
