### ISSUE TITLE
Build error on QT NUC

### ISSUE THREAD

**Issue by emdg05** [interaction-lab/HARMONI#79]
Running `docker-compose -f docker-compose-qt-nuc.yml up` leads to this error:

```
Reading package lists...
W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures were invalid: KEYEXPIRED 1622248854
W: The repository 'http://packages.ros.org/ros/ubuntu xenial InRelease' is not signed.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  ros-kinetic-joint-state-publisher-gui
0 upgraded, 1 newly installed, 0 to remove and 387 not upgraded.
Need to get 11.9 kB of archives.
After this operation, 55.3 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  ros-kinetic-joint-state-publisher-gui
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c APT_INSTALL="apt-get install -y --no-install-recommends" &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive $APT_INSTALL     ros-kinetic-joint-state-publisher-gui     && rm -rf -- /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'harmoni_full' failed to build : Build failed
```

**Comment by micolspitale93** [comment]
> Running `docker-compose -f docker-compose-qt-nuc.yml up` leads to this error:
> 
> ```
> Reading package lists...
> W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures were invalid: KEYEXPIRED 1622248854
> W: The repository 'http://packages.ros.org/ros/ubuntu xenial InRelease' is not signed.
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following NEW packages will be installed:
>   ros-kinetic-joint-state-publisher-gui
> 0 upgraded, 1 newly installed, 0 to remove and 387 not upgraded.
> Need to get 11.9 kB of archives.
> After this operation, 55.3 kB of additional disk space will be used.
> WARNING: The following packages cannot be authenticated!
>   ros-kinetic-joint-state-publisher-gui
> E: There were unauthenticated packages and -y was used without --allow-unauthenticated
> The command '/bin/sh -c APT_INSTALL="apt-get install -y --no-install-recommends" &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive $APT_INSTALL     ros-kinetic-joint-state-publisher-gui     && rm -rf -- /var/lib/apt/lists/*' returned a non-zero code: 100
> ERROR: Service 'harmoni_full' failed to build : Build failed
> ```
Have you solved it? Or are you stiil facing this issue on the NUC?

**Comment by emdg05** [comment]
I was able to get around it by pulling instead of building but I believe the build issue is still there

**Comment by chrismbirmingham** [comment]
This might be related to #84, I have rebuilt and am pushing for the arm builds, will need to try for amd.

**Comment by chrismbirmingham** [comment]
Scratch the second part there, the pushes I am making should fix for the nuc.

**Comment by chrismbirmingham** [comment]
This should be fixed, please reopen if the issue persists.
