### ISSUE TITLE
Cannot run speech-to-text service

### ISSUE THREAD

**Issue by micolspitale93** [interaction-lab/HARMONI#8]
When I tried to launch the stt service, testing it with the audio file recorded from the microphone (harmoni_stt/temp_data/test.wav) with the following command in the ros_w2l terminal (after running the` bash get_w2l_model.sh` as well):
`roslaunch harmoni_stt stt_service.launch test:=true`

I got this error:
`'Started features model file loading ... \n' b"terminate called after throwing an instance of 'std::runtime_error'\n  what():  failed to open feature file=/root/model/feature_extractor.bin for reading\nAborted (core dumped)\`

**Comment by chrismbirmingham** [comment]
Thanks for bringing this up. The get_w2l_model.sh is meant to be run in the host computer. I will modify so it will be downloaded into the container instead of mounting.

**Comment by chrismbirmingham** [comment]
On second thought, I believe this should be the expected behavior (downloading to the local computer then mounting. If we want to change this we also need to change the docker-compose files.
