### ISSUE TITLE
Face configuration documentation on QT

### ISSUE THREAD

**Issue by emdg05** [interaction-lab/HARMONI#83]
The documentation for configuring the face on a QT says to run
`roslaunch harmoni_face face.launch`

However, it should be
`roslaunch harmoni_face face_service.launch`

Additionally, the rosrun lines on both NUC and PI seem to be unnecessary to launch the face.

**Comment by micolspitale93** [comment]
Thank you I'll fix it.
The rosrun only needs to handle the automatic launch of the face when the QT powers on.

**Comment by micolspitale93** [comment]
Fixed
